### ISSUE TITLE
手動でドラム音を鳴らすとBGMが小さくなる。

### ISSUE THREAD

**Issue by DTXMania** [DTXMania/DTXmatixx#1]
手動演奏時、ドラム音（電子ドラムの音ではなくサウンドファイルで提供される音）を鳴らすと、ドラム音が鳴っている間だけBGMの音量が小さくなる。

もしかしたら、聞き取れないだけで、自動演奏時にも発生しているかもしれない。

**Comment by kumakamikoubou** [comment]
WASAPI共有モードのリミッターAPO | PHILE WEBコミュニティ
http://community.phileweb.com/mypage/entry/2721/20101113/21492/

ドラム音が鳴ってる間だけBGMの音量が小さくなる現象は、このリミッターのせいっぽい。

共有モードにしたのが裏目に出たのか
音割れを防げてよかったのか

**Comment by kumakamikoubou** [comment]
BGMとドラム音の音量バランスはDTXの当初から今も続く「譜面製作者側の課題」と見てるんで、再生側で勝手に正規化したりするようなことはしたくないねー。

そういう譜面は、排他モードで再生しても割れる可能性が高い。（例外あり）

**Comment by DTXMania** [comment]
Release 018 で修正。
