### ISSUE TITLE
thumb.pngが置いてあってかつDTX側のPREIMAGEで指定したファイル名と異なっていると絶対に読み込みで落ちる。

### ISSUE THREAD

**Issue by DTXMania** [DTXMania/DTXmatixx#16]
逆にPREIMAGE記述がthumb.pngでファイル名が異なる(またはthumb.pngの)場合はDTXファイルの読み込みに失敗する。

**Comment by kumakamikoubou** [comment]
現在のDTXmatixxではPREIMAGEをガン無視するので、読み込みに失敗するのはまた別の条件があるのでは？
とりあえず、set.def を使っていて、かつthumb画像があった場合に読み込みに失敗する不具合は修正しました。

**Comment by DTXMania** [comment]
Rel004確認。PREIMAGE関連チェック
PREIMAGEにthumb、実ファイルもthumb→OK
PREIMAGEにthumb以外、実ファイルもthumb以外(パス一致)→Pre絵NotFound扱い
PREIMAGEにthumb、実ファイルはthumb以外→エラー
PREIMAGEにthumb以外、実ファイルもthumb以外(不一致)→エラー
PREIMAGEのファイル名不一致だとエラー落ちで確定

ツイッターから。
