### ISSUE TITLE
縁取り文字の一部が尖って表示される。

### ISSUE THREAD

**Issue by DTXMania** [DTXMania/DTXmatixx#2]
字体や文字サイズによっても異なる様子。

現状、DirectWrite のカスタムテキストレンダラを自作して縁取り描画しているが、形状（パス）はシステムから取得したものをそのまま使っているため、もともとのパスがおかしいのかもしれない。

**Comment by limyz** [comment]
Can you upload an image for this issue?
画像をアップロードできますか？

**Comment by kumakamikoubou** [comment]
こんな感じになります。

![sample1](https://user-images.githubusercontent.com/18201754/32442087-72d16fa8-c33d-11e7-8bc7-a4b4a54034af.jpg)
![sample2](https://user-images.githubusercontent.com/18201754/32442091-7604b572-c33d-11e7-8af0-6c6c2a03fb2b.jpg)
