### ISSUE TITLE
全く起動しません。

### ISSUE THREAD

**Issue by tsKas39** [DTXMania/DTXmatixx#53]
バージョン015のsetup.exeを実行し、デフォルトのままインストール後、
実行しても起動しません。
特にエラーや警告ダイアログは表示せず、少しビジーカーソルが表示された後、何も起きません。

環境は以下の通りです。
Windows 10 pro 64bit 1709.16299.371
core i5 8400

**Comment by DTXMania** [comment]
起動時に何か起きるとそうなります。

とりあえず、ログファイルが出力されてるかもしれないので、あるかどうかご確認いただけますか？

[スタート] を**右**クリック → [ファイル名を指定して実行] → `%appdata%\dtxmatixx\logs` と入力して [Ok] 

![execute](https://user-images.githubusercontent.com/18201754/39180402-ba8ab3ac-47f1-11e8-9ff9-fad81590bb4b.png)

エクスプローラーが開けば、中に `.txt` ファイルがあるかもです。

「見つかりません」と言われたり中身が空っぽだったりしたら、残念ながらログは出てませんので、別の診断が必要です。

**Comment by tsKas39** [comment]
ありがとうございます。
ログを確認したところ、Informationしか出ていませんでした。

[INFORMATION] 14:30:32 [01,0x2b18(描画)]
[INFORMATION] 14:30:32 [01,0x2b18(描画)]======== アプリケーションを起動します。 ========
[INFORMATION] 14:30:32 [01,0x2b18(描画)]FDK.UI.Framework.On活性化() --> 開始
[INFORMATION] 14:30:32 [01,0x2b18(描画)]FDK.UI.Framework.On活性化() <-- 終了

**Comment by DTXMania** [comment]
むう……
グラフィック周りには問題がなかったことぐらいしか分かりません。
さすがにログをサボりすぎました。

近々ログ出力を増やしてみますので、もうしばしお待ちを。

**Comment by tsKas39** [comment]
016にバージョンを上げたところ
Configration.jsonが見つからないという旨のログが出力されました。
ご確認よろしくお願い致します。

========================
DTXMania matixx 016
========================
Microsoft Windows 10 Pro 1709(Fall Creators Update), 10.0.16299
RAM: 15.92 GB 中 13.73 GB 利用可能
.NET Framework: 4.7.1以降 (461308)

[INFORMATION] 9:37:20 [01,0x1494(描画)] DTXmatixx.App..ctor() --> 開始
[INFORMATION] 9:37:20 [01,0x1494(描画)] | DTXmatixx.設定.システム設定.復元する() --> 開始
[INFORMATION] 9:37:20 [01,0x1494(描画)] | DTXmatixx.設定.システム設定.復元する() <-- 終了
[INFORMATION] 9:37:20 [01,0x1494(描画)] DTXmatixx.App..ctor() <-- 終了

====> 未処理の例外が検出されました。

System.IO.FileNotFoundException: ファイル 'C:\Users\*******\AppData\Roaming\DTXMatixx\Configuration.json' が見つかりませんでした。
ファイル名 'C:\Users\*******\AppData\Roaming\DTXMatixx\Configuration.json' です。'C:\Users\*******\AppData\Roaming\DTXMatixx\Configuration.json'
   場所 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   場所 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   場所 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   場所 System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   場所 System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   場所 System.IO.File.ReadAllText(String path)
   場所 DTXmatixx.設定.システム設定.復元する()
   場所 DTXmatixx.App..ctor()
   場所 DTXmatixx.Program.Main()

**Comment by DTXMania** [comment]
ありがとうございます。
015 でコンフィグファイルを json に変えた際のミスのようです。

リリース 017 で更新されていると思いますので、ご確認をお願いします。

**Comment by tsKas39** [comment]
起動確認できました。
ありがとうございます。

**Comment by DTXMania** [comment]
ご確認アリがどうございました！
