### ISSUE TITLE
起動できません。

### ISSUE THREAD

**Issue by tintane** [DTXMania/DTXmatixx#54]
DTXMania matixx 017、及び018で試してみましたが状況は同じのようです。
以下、ログになります

========================
DTXMania matixx 018
========================
Microsoft Windows 7 Home Premium  6.1.7601
RAM: 15.92 GB 中 12.51 GB 利用可能
.NET Framework: 4.7.1以降 (461814)

====> 未処理の例外が検出されました。

System.ComponentModel.Win32Exception (0x80004005): ウィンドウのハンドルを作成中にエラーが発生しました。
   場所 System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   場所 System.Windows.Forms.Control.CreateHandle()
   場所 System.Windows.Forms.Form.CreateHandle()
   場所 System.Windows.Forms.Control.get_Handle()
   場所 FDK.ApplicationForm..ctor(SizeF 設計画面サイズ, SizeF 物理画面サイズ, Boolean 深度ステンシルを使う)
   場所 DTXmatixx.App..ctor()
   場所 DTXmatixx.Program.Main()

自分はこういった事に全く明るくないので報告することしかできず、申し訳ないです。
もし何か解決策がありましたら、返答お願いいたします。

**Comment by DTXMania** [comment]
報告ありがとうございます。ＦＲＯＭです。

残念ながら、DTXMania matixx は Windows 7 では動作しないのです。
Windows 10 でないと動作しないのです。
申し訳ないです。

**Comment by tintane** [comment]
そうなんですね...基本的な部分の確認が取れておらず、申し訳ございません。
返答ありがとうございました。

**Comment by tintane** [comment]
そうなんですね...基本的な部分の確認が取れておらず、申し訳ございません。
返答ありがとうございました。
